In [1]:
import torch 

x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [2]:
y = x + x
y

tensor([2, 4, 6, 8])

In [3]:
import syft as sy

In [4]:
hook = sy.TorchHook(torch)

In [6]:
torch.tensor([1,2,3,5])


tensor([1, 2, 3, 5])

In [9]:
#making a virtual worker 
bob = sy.VirtualWorker(hook, id = "bob")

In [10]:
bob._objects

{}

In [12]:
x = torch.tensor([1,2,3,4,5])

In [13]:
x = x.send(bob)

In [14]:
bob._objects

{79853475728: tensor([1, 2, 3, 4, 5])}

In [15]:
x.location

<VirtualWorker id:bob #objects:1>

In [21]:
x.location == bob


False