In [4]:
#imports
import numpy as np
import torch as th
import syft as sy

In [5]:
#set the hook 
hook =sy.TorchHook(th)


In [6]:
#import the optimizer and ane network
from torch import nn,optim

In [9]:
#create virtual workers 
bob = sy.VirtualWorker(hook,id = "bob").add_worker(sy.local_worker)
alice = sy.VirtualWorker(hook, id= "alice").add_worker(sy.local_worker)
secure_worker = sy.VirtualWorker(hook, id= "secure_worker").add_worker(sy.local_worker)

Worker me already exists. Replacing old worker which could cause                     unexpected behavior
Worker me already exists. Replacing old worker which could cause                     unexpected behavior
Worker me already exists. Replacing old worker which could cause                     unexpected behavior


In [36]:
#creating the tensor
x = th.tensor([1,2,3,4])
y = th.tensor([2,-1,1,0])



In [37]:
#share the tensor
x = x.share(bob,alice, crypto_provider=secure_worker)
y = y.share(bob,alice, crypto_provider=secure_worker)

In [38]:
#arthemetic computation
z = x+y 
z.get()


tensor([3, 1, 4, 4])

In [39]:
#subtraction of the tensor
z = x- y
z.get()

tensor([-1,  3,  2,  4])

In [40]:
#comparision algorithm for the tesnsor
z = x < y
z.get()

tensor([1, 0, 0, 0])

In [41]:
#comparision algorithm for the tesnsor
z = x > y
z.get()

tensor([0, 1, 1, 1])