### The making of an empty tensor in pytorch 

In [26]:
import torch 

x = torch.empty(4,4)

In [27]:
x_0 = torch.zeros(2,2)
x_1 = torch.ones(1,1)
x_2 = torch.rand(3,3)
x_3 = torch.randn(4,4 , dtype = torch.float) #sepcify the data type as well 
x_4 = torch.tensor([1,2,3,5])


## Arthimetic Operation 

- every function that has a _ will do inplace operation


In [31]:
# element wise operations 

x_5 = torch.rand(3,3)

x_6 = torch.rand(3,3)

x_5 + x_6

add = torch.add(x_5,x_6) #same element wise operation

sub = torch.sub(x_5, x_6) #same element wise operation sub_

### Indexing the tensor 

In [37]:
x_7 = torch.rand(4,3)

print(x_7)
print(x_7[:,0])  #first column 

print(x_7[1:,]) # first row and all the below

tensor([[0.8222, 0.5287, 0.5656],
        [0.6511, 0.8807, 0.2474],
        [0.0549, 0.1116, 0.9707],
        [0.1621, 0.8920, 0.2312]])
tensor([0.8222, 0.6511, 0.0549, 0.1621])
tensor([[0.6511, 0.8807, 0.2474],
        [0.0549, 0.1116, 0.9707],
        [0.1621, 0.8920, 0.2312]])


### Reshpae the tensor 

In [41]:
x_8 = torch.rand(4,4)
x_9 = x_8.view(-1,8)  #will automiticall do the reshape

print(x_9)

tensor([[0.9824, 0.2287, 0.7911, 0.3397, 0.1600, 0.3239, 0.3814, 0.3864],
        [0.2595, 0.5018, 0.5136, 0.6512, 0.0252, 0.7441, 0.7329, 0.3545]])


### Making the numpy array 

In [46]:
x_10 = x_9.numpy()

x_11 = torch.from_numpy(x_10)  #again type cast to torch

In [51]:
x_12 = [1,2,3,4,5,6]

x_14 = torch.tensor(x_12)  #from python list to torch tensor


### For making the Grad true

In [52]:
x_15 = torch.ones(3,3, requires_grad= True)

## Pytorch autograd 


In [54]:
x_16 = torch.rand(3 , requires_grad= True)

## Process 
- Forward pass to compute the loss
- compute the local gradient 
- Backward pass to compute the derivate using the chain rule

### Torch linear regression 

In [58]:
import torch.nn as nn  #neural network module 

import numpy as np 

#import the data sets 
from sklearn import datasets
import matplotlib.pyplot as ply


### make the data 

In [69]:
#prepare the data 
x_numpy , y_numpy = datasets.make_regression(n_samples= 100 , n_features=1 , noise = 20, random_state= 1)

#conversion of the data type 

X = torch.from_numpy(x_numpy.astype(np.float32))
Y = torch.from_numpy(y_numpy.astype(np.float32))

Y = Y.view(Y.shape[0],1)


In [71]:
#make the features 

n_samples , n_features = X.shape

input_size = n_features
output_size = 1


### Make the model

In [72]:
#model 

model = nn.Linear(input_size,output_size)

### Loss and the optimizer 

In [77]:
criterion = nn.MSELoss() #the loss function 
learning_rate = 0.01
optmizer = torch.optim.SGD(model.parameters(), lr = learning_rate)  #linear regression model

### Training Epochs
- forward pass , compiute prediction and loss
- backward pass , gradients calculation
- update weights


##### After the backward optmizer step we should zero the gradient 

In [82]:
#training loops 
n_epochs = 100
#making the traiing loop 

for iter in range(n_epochs):

    #forward pass and loss

    y_pred = model(X)

    loss = criterion(y_pred , Y) #loss calculation

    #backward pass

    loss.backward()

    #update 

    optmizer.step()

    optmizer.zero_grad() #make the gradient zero

    #printing the loss 

    if (iter+1) % 10 == 0:

        print("loss" , loss.item())

loss 397.1680908203125
loss 379.7626647949219
loss 367.0566101074219
loss 357.7777099609375
loss 350.9995422363281
loss 346.0467529296875
loss 342.4266357421875
loss 339.78009033203125
loss 337.8448486328125
loss 336.42938232421875


### Implementing the logistic regression 

In [111]:
#importing the new datasets
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [112]:
#prepare the dataset 

bc = datasets.load_breast_cancer()

x, y = bc.data, bc.target  #we get the 

n_samples, n_features = x.shape 

In [113]:
#train test split 

x_train, x_test , y_train , y_test = train_test_split(x,y , test_size = 0.2 , random_state = 1234)

#scale the features 

sc  = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)



x_train = torch.from_numpy(x_train.astype(np.float32))

x_test = torch.from_numpy(x_test.astype(np.float32))

y_train = torch.from_numpy(y_train.astype(np.float32))

y_test = torch.from_numpy(y_test.astype(np.float32))


### Make the model 

In [114]:
# 1 make the model

class Logistic_regression(nn.Module):

    def __init__(self,n_features):
        super(Logistic_regression,self).__init__()

        #making the layer

        self.linear = nn.Linear(n_features, 1)

    #making the forward function 

    def forward(self,x):
        y_pred = torch.sigmoid(self.linear(x))

        return y_pred

In [115]:
#initialize the model

model = Logistic_regression(n_features)

In [116]:
#making the loss function 

# step 2  loss and optmizer 

criterion = nn.BCELoss()

optmizer = torch.optim.SGD(model.parameters() , lr = 0.01)

In [117]:
# 3 step to do the training loop 
num_epochs = 100 

for epoch in range(num_epochs):

    #for ward pass and loss calculation 

    y_pred = model(x_train)

    loss = criterion(y_pred, y_train)


    #backward pass and optimizer 

    loss.backward()


    #updates 

    optmizer.step()

    #empty the gradient

    optmizer.zero_grad()

    if (epoch + 1) % 10 == 0:

        print(loss.item())

        



/home/abhi/anaconda3/lib/python3.8/site-packages/torch/nn/modules/loss.py:498: UserWarning: Using a target size (torch.Size([455])) that is different to the input size (torch.Size([455, 1])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)


0.744284451007843
0.5653871893882751
0.4635038375854492
0.3991164267063141
0.3548092544078827
0.32235053181648254
0.2974352538585663
0.2776147127151489
0.2613987326622009
0.24783164262771606
