In [58]:
#interplotaion
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

x = torch.randint( 0,3 , (2,2))

y = x.view(1,2,2)
y = y.to(torch.double)
print("tensor")
print(y)

out = F.interpolate(y, size = 4, mode= 'linear')

z = y.view(1,1,2,2)

out_2 = F.interpolate(z , size= 4, mode= 'bilinear')

out_3 = F.interpolate(z , size =4, mode = "bicubic")

out_4 = F.interpolate(z, size= 4, mode = "nearest" )

#--------------------------------------------------------------#
print("linear")
print(out)
print("bilinear")
print(out_2)
print("bicubic")
print(out_3)
print("nearest")
print(out_4)

tensor
tensor([[[2., 1.],
         [1., 1.]]], dtype=torch.float64)
linear
tensor([[[2.0000, 1.7500, 1.2500, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000]]], dtype=torch.float64)
bilinear
tensor([[[[2.0000, 1.7500, 1.2500, 1.0000],
          [1.7500, 1.5625, 1.1875, 1.0000],
          [1.2500, 1.1875, 1.0625, 1.0000],
          [1.0000, 1.0000, 1.0000, 1.0000]]]], dtype=torch.float64)
bicubic
tensor([[[[2.2221, 1.8550, 1.2505, 0.8834],
          [1.8550, 1.5982, 1.1752, 0.9184],
          [1.2505, 1.1752, 1.0513, 0.9761],
          [0.8834, 0.9184, 0.9761, 1.0111]]]], dtype=torch.float64)
nearest
tensor([[[[2., 2., 1., 1.],
          [2., 2., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]], dtype=torch.float64)


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=linear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for detai