In [1]:
import torch
import torch.nn.functional as F
import torch.nn as nn
x = torch.arange(1, 5, dtype=torch.float32).view(1,1, 2, 2)
m = nn.Upsample(scale_factor=2, mode='nearest')
print(x)

tensor([[[[1., 2.],
          [3., 4.]]]])


In [2]:
m(x) #deafault nearest

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [3]:
m = nn.Upsample(scale_factor=2, mode='bilinear') 
m(x)

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)


tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])

In [4]:
m = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
m(x)

tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])

In [12]:
x = x.view(1,2,2)

m = nn.Upsample(scale_factor = 2, mode = 'linear' )
m(x)

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=linear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)


tensor([[[1.0000, 1.2500, 1.7500, 2.0000],
         [3.0000, 3.2500, 3.7500, 4.0000]]])

In [24]:
y = x.view(1,1,2,2)
print(y.shape)
m = nn.Upsample(scale_factor = 2, mode = 'bicubic' )
m(y)

torch.Size([1, 1, 2, 2])


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)


tensor([[[[0.6836, 1.0156, 1.5625, 1.8945],
          [1.3477, 1.6797, 2.2266, 2.5586],
          [2.4414, 2.7734, 3.3203, 3.6523],
          [3.1055, 3.4375, 3.9844, 4.3164]]]])